In [ ]:
import numpy as np

The tensordot() function calculates the dot product along specified axes of the array_like object.
**Meaning**:It sums the product of a given two tensors a and b over the axes specified by a_axes and b_axes

In [14]:
arr1 = np.arange(8).reshape(4,2)
arr1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [15]:
arr2 = np.arange(2,10).reshape(2,4)
arr2

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [16]:
tendot = np.tensordot(arr1, arr2, axes = ([1,0], [0,1]) )
tendot

array(182)

The Third arguments means a single non-negative integer like scalar.

In [ ]:
a = np.arange(8).reshape(4,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [17]:
b = np.arange(2,10).reshape(2,4)
b

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [18]:
tensdot = np.tensordot(arr1, arr2, axes=1) #for calculating tensor dot product
tensdot

array([[ 6,  7,  8,  9],
       [22, 27, 32, 37],
       [38, 47, 56, 65],
       [54, 67, 80, 93]])

The difference between tensor product and tensor dot product is that the tensor product takes an element from the first array and multiple it to each element in the second array and so on (direct product of two vectors), while the tensor dot product combines two vectors into a scalar number 


In [19]:
tensdot = np.tensordot(arr1, arr2, axes=0) #for calculating tensor product
tensdot

array([[[[ 0,  0,  0,  0],
         [ 0,  0,  0,  0]],

        [[ 2,  3,  4,  5],
         [ 6,  7,  8,  9]]],


       [[[ 4,  6,  8, 10],
         [12, 14, 16, 18]],

        [[ 6,  9, 12, 15],
         [18, 21, 24, 27]]],


       [[[ 8, 12, 16, 20],
         [24, 28, 32, 36]],

        [[10, 15, 20, 25],
         [30, 35, 40, 45]]],


       [[[12, 18, 24, 30],
         [36, 42, 48, 54]],

        [[14, 21, 28, 35],
         [42, 49, 56, 63]]]])